# name: Scrape latest data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Prepare the environment
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Install requirements, so Python script can run
      - name: Install requirements
        run: pip install -r requirements.txt

      # Step 3: Install ipykernel package
      - name: Install ipykernel
        run: pip install ipykernel

      # Step 4: Set up Python 3 kernel for Jupyter
      - name: Set up Python 3 kernel
        run: python3 -m ipykernel install --user --name=python3

      # Step 5: Run Jupyter Notebook with specified kernel
      - name: Run scraper
        run: jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --to notebook --execute InspectionDatabase.ipynb

      # Step 6: Commit files
      - name: Commit files
        run: |
          git config remote.origin.url  https://github.com/Kunle-Falayi/restaurants-scraper1.git
          git
