name: Scrape and Publish to Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  scrape_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests numpy pandas google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Set up Google Service Account Key
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > key.json

      - name: Run scraper
        run: |
          # Run your scraper script here

      - name: Publish to Google Sheets
        env:
          GOOGLE_APPLICATION_CREDENTIALS: key.json
        run: |
          python publish_to_google_sheets.py  # name for google sheets publishing script
